(() => {
  const STORAGE_KEY='kino-finance-mvp-v1';
  const PIPELINE=[['','Без статуса'],['planned','Планирую подаваться'],['submitted','Заявка подана'],['waiting','Жду результаты'],['rejected','Не подходит']];
  const MONTHS={января:0,февраля:1,марта:2,апреля:3,мая:4,июня:5,июля:6,августа:7,сентября:8,октября:9,ноября:10,декабря:11};
  let items=[]; const byId=new Map(); let state=loadState();
  const page=document.body.dataset.workspace;

  function loadState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return{records:p.records||{},compare:Array.isArray(p.compare)?p.compare:[]}}catch(_){return{records:{},compare:[]}}}
  function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
  function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function urlFor(v){try{if(!v||v==='—')return'';const u=new URL(/^https?:\/\//i.test(v)?v:`https://${v}`);return /^https?:$/.test(u.protocol)?u.href:''}catch(_){return''}}
  function parseDates(v){const t=String(v||'').toLowerCase().replace(/ё/g,'е');const years=[...t.matchAll(/\b(20\d{2})\b/g)].map(m=>+m[1]);const fallback=years.at(-1)||new Date().getFullYear();const names=Object.keys(MONTHS).join('|');const re=new RegExp(`(\\d{1,2})(?:\\s*[–—-]\\s*(\\d{1,2}))?\\s+(${names})(?:\\s+(20\\d{2}))?`,'g');const out=[];for(const m of t.matchAll(re)){const d=new Date(+(m[4]||fallback),MONTHS[m[3]],+(m[2]||m[1]),23,59,59);out.push(d)}return out.sort((a,b)=>a-b)}
  function nextDate(item){const now=new Date();now.setHours(0,0,0,0);const arr=[...parseDates(item.deadline_text).map(d=>({date:d,kind:'Дедлайн подачи'})),...parseDates(item.defense_date).map(d=>({date:d,kind:'Защита / питчинг'})),...parseDates(item.results_date).map(d=>({date:d,kind:'Публикация результатов'}))].filter(x=>x.date>=now).sort((a,b)=>a.date-b.date);return arr[0]||null}
  function formatDate(d){return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}
  function statusLabel(v){return PIPELINE.find(x=>x[0]===v)?.[1]||'Без статуса'}
  function statusOptions(v){return PIPELINE.map(([key,label])=>`<option value="${key}"${key===v?' selected':''}>${label}</option>`).join('')}
  function selectedIds(){return Object.entries(state.records).filter(([,r])=>page==='favorites'?r.favorite:Boolean(r.status)).map(([id])=>id).filter(id=>byId.has(id))}
  function finance(item){return item.max_amount_text||'Условия уточняются'}
  function card(item){const rec=state.records[item.id]||{};const next=nextDate(item);const source=urlFor(item.link);return `<article class="workspace-card" data-id="${item.id}"><div class="workspace-card-main"><strong>${esc(item.org||item.title)}</strong><small>${esc(item.program||item.what_for||'')}</small></div><div class="workspace-card-finance"><b>${esc(finance(item))}</b><span>${esc(item.coverage_pct||item.returnable||'')}</span></div><div class="workspace-card-date"><b>${next?formatDate(next.date):'—'}</b><span>${next?esc(next.kind):'Нет подтверждённой будущей даты'}</span></div>${page==='submissions'?`<select class="workspace-status" data-status>${statusOptions(rec.status||'')}</select>`:`<div><span class="workspace-dot"></span><span style="font-size:9px;font-weight:650">В избранном</span></div>`}<div class="workspace-card-actions">${source?`<a class="workspace-btn" href="${esc(source)}" target="_blank" rel="noopener">Источник</a>`:''}<button type="button" data-ics ${next?'':'disabled'}>.ICS</button><button type="button" data-remove>${page==='favorites'?'Убрать':'Удалить'}</button></div></article>`}
  function groupSubmissions(ids){const order=['planned','submitted','waiting','rejected'];return order.map(status=>{const subset=ids.filter(id=>(state.records[id]?.status||'')===status);if(!subset.length)return'';return `<section class="workspace-group"><div class="workspace-group-head"><h2>${statusLabel(status)}</h2><span>${subset.length}</span></div><div class="workspace-list">${subset.map(id=>card(byId.get(id))).join('')}</div></section>`}).join('')}
  function renderSummary(ids){const root=document.querySelector('[data-summary]');if(!root)return;if(page==='favorites'){root.innerHTML=`<div class="workspace-summary-item"><b>${ids.length}</b><span>сохранено</span></div><div class="workspace-summary-item"><b>${ids.filter(id=>nextDate(byId.get(id))).length}</b><span>с будущими датами</span></div>`}else{const vals=ids.map(id=>state.records[id]?.status);root.innerHTML=`<div class="workspace-summary-item"><b>${ids.filter(id=>state.records[id]?.status!=='rejected').length}</b><span>активных</span></div><div class="workspace-summary-item"><b>${vals.filter(v=>v==='submitted').length}</b><span>подано</span></div><div class="workspace-summary-item"><b>${vals.filter(v=>v==='waiting').length}</b><span>ждут результатов</span></div>`}}
  function render(){const ids=selectedIds();renderSummary(ids);const root=document.querySelector('[data-workspace-list]');if(!root)return;if(!ids.length){root.innerHTML=`<div class="workspace-empty">${page==='favorites'?'Здесь появятся источники, которые вы добавите в избранное. Откройте каталог и нажмите «В избранное» в нужной карточке.':'Здесь появятся программы, которым вы назначите статус подачи в каталоге источников.'}</div>`;return}root.innerHTML=page==='submissions'?groupSubmissions(ids):`<div class="workspace-list">${ids.map(id=>card(byId.get(id))).join('')}</div>`;bindRows()}
  function bindRows(){document.querySelectorAll('.workspace-card').forEach(row=>{const id=row.dataset.id;row.querySelector('[data-status]')?.addEventListener('change',e=>{const r=state.records[id]||{};r.status=e.target.value;r.updatedAt=new Date().toISOString();if(!r.status&&!r.favorite)delete state.records[id];else state.records[id]=r;saveState()});row.querySelector('[data-remove]')?.addEventListener('click',()=>{const r=state.records[id]||{};if(page==='favorites')r.favorite=false;else r.status='';if(!r.favorite&&!r.status)delete state.records[id];else state.records[id]=r;saveState()});row.querySelector('[data-ics]')?.addEventListener('click',()=>downloadIcs([byId.get(id)]))})}
  function icsEscape(v){return String(v||'').replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\n/g,'\\n')}
  function icsDate(d){return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
  function downloadIcs(list){const events=list.map(item=>({item,next:nextDate(item)})).filter(x=>x.next);if(!events.length)return toast('Нет подтверждённых будущих дат');const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Kino Finance Russia//Workspace//RU','CALSCALE:GREGORIAN','METHOD:PUBLISH'];events.forEach(({item,next})=>{const end=new Date(next.date);end.setDate(end.getDate()+1);lines.push('BEGIN:VEVENT',`UID:${item.id}-${icsDate(next.date)}@kino-finance-russia`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${icsDate(next.date)}`,`DTEND;VALUE=DATE:${icsDate(end)}`,`SUMMARY:${icsEscape(next.kind+': '+item.org+' — '+(item.program||item.title||''))}`,`DESCRIPTION:${icsEscape(item.deadline_text||item.status||'')}`);const source=urlFor(item.apply_link)||urlFor(item.link);if(source)lines.push(`URL:${icsEscape(source)}`);lines.push('END:VEVENT')});lines.push('END:VCALENDAR');downloadBlob(lines.join('\r\n')+'\r\n',page==='favorites'?'izbrannoe.ics':'moi-podachi.ics','text/calendar;charset=utf-8')}
  function downloadBlob(content,name,type){const b=new Blob([content],{type});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
  function toast(text){const n=document.createElement('div');n.className='workspace-toast';n.textContent=text;document.body.append(n);setTimeout(()=>n.remove(),2200)}
  function clearAll(){const ids=selectedIds();ids.forEach(id=>{const r=state.records[id]||{};if(page==='favorites')r.favorite=false;else r.status='';if(!r.favorite&&!r.status)delete state.records[id];else state.records[id]=r});localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
  async function boot(){const responses=await Promise.all(Array.from({length:10},(_,i)=>fetch(`./data-${String(i).padStart(2,'0')}.json`,{cache:'no-store'})));const parts=await Promise.all(responses.map(r=>r.ok?r.json():{items:[]}));items=parts.flatMap(p=>p.items||[]);items.forEach(i=>byId.set(i.id,i));document.querySelector('[data-download-all]')?.addEventListener('click',()=>downloadIcs(selectedIds().map(id=>byId.get(id))));document.querySelector('[data-clear-all]')?.addEventListener('click',clearAll);render()}
  document.addEventListener('DOMContentLoaded',()=>boot().catch(err=>{console.error(err);document.querySelector('[data-workspace-list]').innerHTML='<div class="workspace-empty">Не удалось загрузить данные справочника.</div>'}))
})();